kind: Service
apiVersion: v1
metadata:
  name: akka-cluster-client-demo-frontend
spec:
  selector:
    app: akka-cluster-client-demo-frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort